extends PanelContainer

signal job_accepted

var job_data: JobData
@onready var job_name: Label = $MarginContainer/VBoxContainer/HBoxContainer2/PartName
@onready var job_amount: Label = $MarginContainer/VBoxContainer/HBoxContainer3/PartAmount
@onready var job_reward: Label = $MarginContainer/VBoxContainer/HBoxContainer/RewardLabel
@onready var job_experience: Label = $MarginContainer/VBoxContainer/HBoxContainer3/PartExperience

func initialize_job(data: JobData) -> void:
	job_data = data
	job_name.text = job_data.job_name
	job_amount.text = "Amount: " + str(job_data.job_amount)
	job_reward.text = "Reward: " + str(job_data.job_reward) + "€"
	job_experience.text = "Experience: " + str(job_data.job_experience)

func _on_accept_job_pressed() -> void:
	job_accepted.emit(self)
